function xreal = forcereal(x, dp)
    xreal = [...
        vectorize(fft2(real(ifft2(boxify(x(:,1), dp.Nx, dp.Nz)))), dp.NxNz)...
        vectorize(fft2(real(ifft2(boxify(x(:,2), dp.Nx, dp.Nz)))), dp.NxNz)...
        vectorize(fft2(real(ifft2(boxify(x(:,3), dp.Nx, dp.Nz)))), dp.NxNz)...
        ];
end
